### ISSUE TITLE
无法点击文章

### ISSUE THREAD

**Issue by dtaliy** [scofieldpeng/docker-typecho#1]
您好，我使用您的项目构建了typecho，版本在1.0+（测试了好几个），安装都是没有问题的，但是无法点击文章，我怀疑是typecho.conf的问题？

在安装的过程中，我使用root用户去登陆数据库的。

以及您说的第六条不是很清楚什么意思，能分享一下您的版本或者说模板地址么？

**Comment by scofieldpeng** [comment]
初始化的时候会要求你输入域名，比如你想你的博客地址是example.com,这里就输入example.com，还有就是docker下的nginx的配置的server_name也写成example.com

**Comment by scofieldpeng** [comment]
另外，typecho的源码建议直接用github上的master分支，release的有问题
